env:
    es2021: true
    node: true
extends:
    - airbnb-base
    - airbnb-typescript/base
    - prettier
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: 2021
    sourceType: module
    project: tsconfig.json
plugins:
    - '@typescript-eslint'
    - prettier
rules:
    prettier/prettier: error
    no-console: off
    import/prefer-default-export: off
    '@typescript-eslint/no-unused-vars': warn
